build:
    nodes:
        analysis:
            environment:
                php:
                    version: 8.1
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
